dist: bionic
language: python
python: 3.8

install:
  - pip install -r requirements.txt

script:
  - sigal build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _build
  on:
    branch: master
