dist: bionic
language: python
python: 3.8

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

install:
  - pip install -r requirements.txt

script:
  - sigal build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _build
  on:
    branch: master
